### ISSUE TITLE
RunRFmix.py 

### ISSUE THREAD

**Issue by leedison1** [armartin/ancestry_pipeline#14]
Hello ,Can you provide RunRFmix.py for me to study? I can't find it in your code. Thank you very much.

**Comment by leedison1** [comment]
Hello, Lady (Sir), I followed the steps you provided to run the code, but when "Run RFMix", I found that the part of code RunRFmix.py was missing, could you please provide it for me to learn? Thank you very much.

**Comment by bgyuris** [comment]
Hi, Can you tell me what was the solution? I cannot find it. Thank you.
