### ISSUE TITLE
RFMix unable to execute binary PopPhased

### ISSUE THREAD

**Issue by ftlin22** [armartin/ancestry_pipeline#4]
Hi,

Would you be able to provide the Makefile for RFMix, so to execute the RFMix software?
I would really appreciate that because I am unable to run PopPhased. 

Thanks,
-Fred

**Comment by armartin** [comment]
Depending on which system you're on, you can compile RFMix in the same folder as the source code as follows:

`g++ -Wall -O3 -ftree-vectorize -fopenmp main.cpp getdata.cpp randomforest.cpp crfviterbi.cpp windowtosnp.cpp -o RFMix_PopPhased`

(just switch out name to do the same for TrioPhased)
